### ISSUE TITLE
include weights in tICA

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#749] opened 2016-03-29 15:47 UTC
Is it possible to add including weights when calculating tICA from multiple trajectories? Each trajectory would have different (non-integer) weights.

**Comment by gph82** [comment] 2016-03-30 13:38
Hi, can you be a bit more specific as to what will happen to the transformed trajectories once you computed your weighted TICA transformation? Normal discretization plus MSM, like in the example notebooks?

**Comment by euhruska** [comment] 2016-03-30 14:54
no MSM, at least, I don't plan to. I want to do then a reweighting step similar to DM-d-MD. That's why the weights are quite important. For that, I only need the TICA coordinates of the points along the trajectories.

**Comment by gph82** [comment] 2016-03-30 16:07
I am not familiar with the new running_covar class, perhaps one could provide it with an array of trajectory weights at initialization and then set `return_trajindex = True` for this iterator
https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/transform/tica.py#L264
and parse that trajindex to `self._covar.add` here:
https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/transform/tica.py#L268

but I am not sure if the running_moments algorithm assumes equal weights. What do you think, @franknoe

**Comment by franknoe** [comment] 2016-03-30 17:29
Don't worry, I'll do it. I just told Eugen to open an issue so that I 
don't forget.

Am 30/03/16 um 18:07 schrieb Guillermo Pérez-Hernández:

> I am not familiar with the new running_covar class, perhaps one could 
> provide it with an array of trajectory weights at initialization and 
> then set |return_trajindex = True| for this iterator
> https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/transform/tica.py#L264
> and parse that trajindex to |self._covar.add| here:
> https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/transform/tica.py#L268
> 
> but I am not sure if the running_moments algorithm assumes equal 
> weights. What do you think, @franknoe https://github.com/franknoe
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/749#issuecomment-203505867

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2016-05-17 18:18
Isn't that just a duplicate of #570?

**Comment by franknoe** [comment] 2016-05-17 18:19
It is indeed!
Feliks is currently working on that.

Am 17/05/16 um 20:18 schrieb Martin K. Scherer:

> Isn't that just a duplicate of #570 
> https://github.com/markovmodel/PyEMMA/issues/570?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/749#issuecomment-219807207

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2016-05-17 18:23
Ok. I'll close the older issue then

**Comment by marscher** [comment] 2017-05-24 21:27
I think we have this now

**Closed as completed by marscher** 2017-05-24 21:27 UTC
Labels: feature-request
