### ISSUE TITLE
inconsistency in feature selection for minimum distance calculation

### ISSUE THREAD

**Issue by nsplattner** [markovmodel/PyEMMA#771] opened 2016-04-11 15:50 UTC
There seems to be an inconsistency in the final feature selection when reading a full trajectory (protein+water) instead of just a protein trajectory. The testcase is the following: minimum distances between two molecules are calculated from the same trajectory: 
a) with a PDB and DCD of the full trajectory 
b) with a PDB and DCD of the protein only of the same trajectory. 
The two trajectories are identical except for the missing waters (i.e. no alignment or other transformations are carried out). A selection of miminum distances is then done in both cases with this statement:

```
feat.add_residue_mindist(residue_pairs=ind_arr, scheme='closest-heavy')
```

The feature looks identical if the feat.describe() option is used. However, when the minimum distances are actually calculated with 

```
inp = coor.source(infile, feat)
```

a different selection of distances is somehow passed to MDtraj. If I check directly the number of atom_pairs passed to the MDtraj compute_distances() function it is smaller in a) than in b), indicating that effectively a different atom selection is used. As a consequence the result also differs.

**Comment by gph82** [comment] 2016-04-14 08:35
Hi Nuria, I'll look into this right away. In the meantime, some questions:
- could you use each original pdbfiles as 1-frame trajectories (infile=pdbfile) and see if this behavior persists. Looks like it's dcd-specific, since feat.describe seem identical.
- could you paste (or describe) the "ind_array". I assume it's the same in both cases? 

If you point me the pdbfiles and some reduced versions of the .dcd files (a single frame will be enough), or email if it's more convenient? I'll try to see what's going on.

Thanks

**Comment by nsplattner** [comment] 2016-04-14 09:19
O.k., I will send you the link to pdb/dcd example files (uploading may be inconvenient) and a script.

Thanks!

**Comment by gph82** [comment] 2016-04-14 14:18
I think I cannot reproduce the exact same error, can you check the notebook and see if it should capture the inconsistency that you found? 

The numbers between both trajectories do differ, but If you look at the last cells, I've reproduced a copy of the full dataset, then reduced it to the protein-only dataset in memory. Then, not only the shape, but also the numbers coincide.

Are both trajectory files the same trajectory?
![snap2](https://cloud.githubusercontent.com/assets/7518004/14531144/7000d3de-025c-11e6-8ef7-76f6a280fed6.png)

**Comment by nsplattner** [comment] 2016-04-14 14:29
I think you can not see the problem a this level. The trajectory I provided is exactly the same, just with a different subset of coordinate stored. I only saw that there is a problem 
a) in the overall result when the feature is calculated (i.e. the minimum distances differ)
b) in the MDtraj compute_distances() routines, modifying the source code to print the number of distance used
The reason for this is that the dimension of the feature is always the same since its the same number of residue pairs for the calculation of minimum distances. However, each minimum distance is the result of calculating a specific number of atom-atom distances. This number differs, but this is not visible in feature dimensions, only at the calculation and the result level.

**Comment by gph82** [comment] 2016-04-14 14:35
ahh..I see now what you meant with "If I check directly the number of atom_pairs passed to the MDtraj compute_distances() function it is smaller in a) than in b)"

Do you think periodic boundary conditions might have something to do with this? We might expose the periodic=True/False in our api to have more control. 

I'll keep looking

**Comment by nsplattner** [comment] 2016-04-14 14:36
I have tested with and without periodic boundaries and the problem stays the same. So I think its unrelated.

**Comment by gph82** [comment] 2016-04-14 15:37
As I expected, this is a problem of the original pbcs of the topfile. If repeat everything with a pdbfile directly extracted from full.pdb (selection=Protein), everything runs as expected. And the outputs numerically coincide. Can you confirm this?

Strangely, the inconsistency persists even with periodic=False in md.compute_contacts (see https://github.com/mdtraj/mdtraj/pull/1072). I'll keep looking. In the meantime, check that with a topfile like described above, your calculations are consistent.

**Comment by nsplattner** [comment] 2016-04-14 16:03
I can confirm this in case the PDB is created by trjconv, but not by VMD. So the problem seems to be the original formatting of the PDB. There is no PBC information directly provided in the PDB (and also it should not be used since the PBC information in the DCD is the one considered.)

Very strange...

**Comment by gph82** [comment] 2016-04-14 17:02
I'll leave this open until we see what the mdtraj developers say.

**Comment by gph82** [comment] 2016-04-14 17:03
oh, and, BTW, as usual, very dangerous to start a sentence with "as I expected"...turns out I was wrong.

**Comment by marscher** [comment] 2018-01-16 13:43
fixed by https://github.com/mdtraj/mdtraj/pull/1072

**Closed as completed by marscher** 2018-01-16 13:43 UTC
Labels: bug, upstream
