### ISSUE TITLE
CK test Error

### ISSUE THREAD

**Issue by sundelinllnl** [markovmodel/PyEMMA#1416] opened 2019-05-21 22:23 UTC
Hi, developers,

I encountered an Error when doing the CK test, msm.cktest(2),
Traceback (most recent call last):
  File "/Users/sun25/miniconda3/envs/pyemma_tutorials/lib/python3.7/site-packages/pyemma/msm/models/msm.py", line 355, in _ensure_eigendecomposition
    m = self._D.shape[0]  # this will raise and exception if self._D doesn't exist yet.
AttributeError: 'MaximumLikelihoodMSM' object has no attribute '_D'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sun25/miniconda3/envs/pyemma_tutorials/lib/python3.7/site-packages/pyemma/msm/estimators/_msm_estimator_base.py", line 848, in cktest
    ck.estimate(self._dtrajs_full)
  File "/Users/sun25/miniconda3/envs/pyemma_tutorials/lib/python3.7/site-packages/pyemma/_base/estimator.py", line 407, in estimate
    self._model = self._estimate(X)
  File "/Users/sun25/miniconda3/envs/pyemma_tutorials/lib/python3.7/site-packages/pyemma/msm/estimators/lagged_model_validators.py", line 169, in _estimate
    self._est.append(self._compute_observables(model, estimator))
  File "/Users/sun25/miniconda3/envs/pyemma_tutorials/lib/python3.7/site-packages/pyemma/msm/estimators/lagged_model_validators.py", line 467, in _compute_observables
    pksub = model.propagate(p0sub, mlag)
  File "/Users/sun25/miniconda3/envs/pyemma_tutorials/lib/python3.7/site-packages/pyemma/msm/models/msm.py", line 487, in propagate
    self._ensure_eigendecomposition(self.nstates)
  File "/Users/sun25/miniconda3/envs/pyemma_tutorials/lib/python3.7/site-packages/pyemma/msm/models/msm.py", line 362, in _ensure_eigendecomposition
    self._compute_eigendecomposition(neig)
  File "/Users/sun25/miniconda3/envs/pyemma_tutorials/lib/python3.7/site-packages/pyemma/msm/models/msm.py", line 322, in _compute_eigendecomposition
    self._p_id = _hash_numpy_array(self.transition_matrix)
  File "/Users/sun25/miniconda3/envs/pyemma_tutorials/lib/python3.7/site-packages/pyemma/util/numeric.py", line 47, in _hash_numpy_array
    x.flags.writeable = old
ValueError: cannot set WRITEABLE flag to True of this array

How to solve this problem?

Thanks

**Comment by ppxasjsm** [comment] 2019-05-22 10:39
I have come across a similar issue, as part of the ck_test on the pyemma tutorial files [this notebook](https://github.com/markovmodel/pyemma_tutorials/blob/master/notebooks/03-msm-estimation-and-validation.ipynb). In particular, using the alanine dipeptide example. I am running on a docker instance on a cloud computing resource. 

I do not get the same error running on my laptop. I have a feeling this may be due to some automatic parallelization. I have 48 visible cores and unless I restrict `its` and clustering to a smaller number of jobs, say n_jobs=2 everything runs very slowly or will occasionally crash with this error:

```
22-05-19 10:35:16 pyemma.msm.estimators.bayesian_msm.BayesianMSM[8] WARNING  Ignored error during estimation: [Errno 12] Cannot allocate memory
WARNING:pyemma.msm.estimators.bayesian_msm.BayesianMSM[8]:Ignored error during estimation: [Errno 12] Cannot allocate memory
22-05-19 10:35:17 pyemma.msm.estimators.bayesian_msm.BayesianMSM[8] WARNING  Ignored error during estimation: [Errno 12] Cannot allocate memory
WARNING:pyemma.msm.estimators.bayesian_msm.BayesianMSM[8]:Ignored error during estimation: [Errno 12] Cannot allocate memory
Process ForkPoolWorker-56:
Process ForkPoolWorker-57:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 127, in worker
    put((job, i, result))
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 127, in worker
    put((job, i, result))
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)

During handling of the above exception, another exception occurred:

BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 132, in worker
    put((job, i, (False, wrapped)))
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 132, in worker
    put((job, i, (False, wrapped)))
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

```
on these lines of code:

```python 
nstates = 4
bayesian_msm = pyemma.msm.bayesian_markov_model(dtrajs, lag=10, dt_traj='1 ps')
pyemma.plots.plot_cktest(bayesian_msm.cktest(nstates), units='ps');
```

**Comment by ppxasjsm** [comment] 2019-05-22 11:08
Ah just saw this issue  #1406, 1.15. numpy does work for me as well.

**Comment by marscher** [comment] 2019-05-22 11:50
duplicate of #1406

**Closed as completed by marscher** 2019-05-22 11:50 UTC
Labels: bug, duplicate

**Comment by sundelinllnl** [comment] 2019-05-22 18:23
I downgraded numpy to 1.15, but I still got the same Errors.

**Comment by sundelinllnl** [comment] 2019-05-22 18:43
Downgrading numpy to 1.15 works on Linux but not on my Mac.
