### ISSUE TITLE
[coor.source] get_output() on list of dcds not working?

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#1068] opened 2017-04-01 15:43 UTC
2.3.2+0.g142fb85.dirty

It seems that there's a problem with the source object when list of dcds are being used. The same code for .xtcs (see below) has no problem:
```python
for ff in flist:
    src = pyemma.coordinates.source(ff, top=top)
    src.get_output(stride=1000)
# No problem here, each file individually, BUT
src = pyemma.coordinates.source(flist, top=top)
src.get_output(stride=1000)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-99bf528e8a7f> in <module>()
      7 #List of first ten
      8 src = pyemma.coordinates.source(flist, top=top)
----> 9 src.get_output(stride=1000)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/_base/iterable.py in get_output(self, dimensions, stride, skip, chunk)
    231                 L = len(chunk)
    232                 if L > 0:
--> 233                     trajs[itraj][it.pos:it.pos + L, :] = chunk[:, dimensions]
    234 
    235                 # update progress

ValueError: could not convert string to float: '1FME-0-protein/1FME-0-protein-000.dcd'
```
The code that works:
```python
src = pyemma.coordinates.source([ff.replace('dcd','xtc') for ff in flist], top=top)
src.get_output(stride=1000)
```

**Comment by marscher** [comment] 2017-04-02 21:36
This is a hilarious behaviour. How does your file list look like?

0. eg. [ff.replace('dcd','xtc') for ff in flist][:n]
1. is flist a numpy array?
2. type(flist[0].replace('dcd', 'xtc')

Somehow the file names are being treated as the actual data, because of some wrong type checking.

**Comment by marscher** [comment] 2017-04-02 21:44
3. from pyemma.coordinates.data import DataInMemory: assert isinstance(src, DataInMemory)

**Comment by marscher** [comment] 2017-04-03 08:09
source(list(flist)) should also do the trick. We should check for numpy string arrays too, or more generic like iterable of str.

**Comment by gph82** [comment] 2017-04-03 14:31
sorry I did not get back earlier. today I'm packed, but I'll try to take a closer look

**Comment by marscher** [comment] 2017-04-03 14:33
I think this one is pretty clear. The source function delegates the filename list to DataInMemory, because it has type ndarray.
We need to distinguish ndarray(str) from ndarray(float).

**Comment by gph82** [comment] 2017-04-03 14:33
but flist was a list created with glob(*dcd)?

**Comment by marscher** [comment] 2017-04-03 14:37
and it has not been converted to a numpy array in the meantime?

**Comment by gph82** [comment] 2017-04-03 14:39
no it had not. I did not store the example because it was out of a live notebook.

**Comment by marscher** [comment] 2017-04-03 14:44
I could only reproduce this, when flist is a numpy array of str. A minimum working example would be nice to have,
but I assume it would be hard to find, because the type checking in source only allows passing "data" of type str,
if and only if the container is a numpy array.

**Comment by gph82** [comment] 2017-04-03 14:45
I think I can do that later. I'm preparing a class on molpx and trying to get out a release before 10:45 (+7 to berlin time).

**Comment by gph82** [comment] 2017-04-03 14:46
BTW @thempel  just told me that he's fighting with dcds?

**Comment by thempel** [comment] 2017-04-03 14:46
... have to report issues with contact features (getting weird output, i.e. contacts are not 0 or 1) with DCD-files as well. I'm analyzing it.

**Comment by thempel** [comment] 2017-04-03 15:18
This seems to be a corrupted DCD-file, so it's probably unrelated to @gph82 's issue. It's just interesting that one gets random output. Even though `mdconvert` reports a possibly corrupted DCD-file, no warning is thrown when loading the data. My output for contact features is e.g. 
```
        [  0.00000000e+00,   1.30435461e-20,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,  -1.71163329e+21,
           2.67776337e+01,   9.20148624e-41,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           1.30435461e-20,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   4.62428493e-44,   0.00000000e+00,
           1.89272366e-19,   0.00000000e+00,  -7.90383559e+11,
           4.55982520e-41,   1.47977118e-42,   0.00000000e+00,
           1.23314265e-42,   0.00000000e+00,   1.21072187e-42,
           0.00000000e+00,  -2.78035661e+09,   4.55982520e-41,
           9.18354962e-41,   1.76182874e-18,   2.80259693e-45,
           0.00000000e+00,   0.00000000e+00,   1.40129846e-45,
           2.80259693e-45,   2.80259693e-45,   2.80259693e-45,
           2.80259693e-45,   0.00000000e+00,   0.00000000e+00,
           1.33963205e+29,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   1.58697811e-25,   0.00000000e+00]
```

**Comment by marscher** [comment] 2017-04-04 20:41
@thempel this is unrelated, yes.
@gph82 python -c "import numpy as np; import pyemma; pyemma.coordinates.source(np.array(['this_does_not_matter.xtc', 'really_it_does_not.dcd'])).get_output()"
 leads to exactly the same stack you've shown.

**Comment by gph82** [comment] 2017-04-04 20:50
okay, thanks so much for investigating...i'm caught up in other stuff, the dcd files where part of a lecture which in the end I gave with the regular ol' xtcs which is what I usually work with. Is this behavior new, though?

**Comment by marscher** [comment] 2017-04-05 11:37
it hasn't changed for two years.

**Comment by gph82** [comment] 2017-04-05 15:17
so....nobody noticed before?

**Comment by marscher** [comment] 2017-04-12 14:09
I'm closing this for now, you can reopen it, if you want to make it a feature request "support numpy str arrays" as input. But as far as I remember we discouraged this case in the beginning.

**Closed as completed by marscher** 2017-04-12 14:09 UTC
