### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#567] opened 2015-09-28 00:32 UTC
When installing now I get an ominous error. Maybe it's connected with issue #560

``````
>>>python setup.py install
...
Processing dependencies for pyEMMA==2.0.1+3.gdbbaac0
Searching for bhmm==0.5.1
Reading https://pypi.python.org/simple/bhmm/
Best match: bhmm 0.5.1
Downloading https://pypi.python.org/packages/source/b/bhmm/bhmm-0.5.1.tar.gz#md5=a4e0e1c9da1915f266c6cecc2b8b907a
Processing bhmm-0.5.1.tar.gz
Writing /tmp/easy_install-eHTXPg/bhmm-0.5.1/setup.cfg
Running bhmm-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-eHTXPg/bhmm-0.5.1/egg-dist-tmp-iC2YcL
Traceback (most recent call last):
  File "setup.py", line 276, in <module>
    setup(**metadata)
  File "/opt/apps/software/MPI/GCC/4.4.7/OpenMPI/1.8.6/Python/2.7.9/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/apps/software/MPI/GCC/4.4.7/OpenMPI/1.8.6/Python/2.7.9/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/apps/software/MPI/GCC/4.4.7/OpenMPI/1.8.6/Python/2.7.9/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 117, in do_egg_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 376, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 600, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 651, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 699, in process_distribution
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 797, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1047, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1059, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 619, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 649, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 834, in install_eggs
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1055, in build_and_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1041, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 204, in run_setup
  File "/opt/apps/software/MPI/GCC/4.4.7/OpenMPI/1.8.6/Python/2.7.9/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 157, in setup_context
  File "/opt/apps/software/MPI/GCC/4.4.7/OpenMPI/1.8.6/Python/2.7.9/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 128, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 106, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 157, in setup_context
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 201, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 231, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 200, in runner
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-eHTXPg/bhmm-0.5.1/setup.py", line 102, in <module>
    import mdtraj
  File "/home/eh22/local/lib/python2.7/site-packages/Cython-0.21.2-py2.7-linux-x86_64.egg/Cython/Build/Dependencies.py", line 729, in cythonize
    aliases=aliases)
  File "/home/eh22/local/lib/python2.7/site-packages/Cython-0.21.2-py2.7-linux-x86_64.egg/Cython/Build/Dependencies.py", line 628, in create_extension_list
    raise TypeError(pattern)
TypeError: <setuptools.extension.Extension instance at 0x7f0f6c55afc8>```
``````

**Comment by euhruska** [comment] 2015-09-28 00:47
Not sure what this was, but I installed bhmm separately, reinstalled everything and it works.
It just gives an warning:

``````
/home/eh22/modules/PyEMMA/pyemma/coordinates/util/stat.py:31: DeprecationWarning: Call to deprecated function hist. Called from pyemma.coordinates.util.stat line 31. Please use pyemma.coordinates.histogram()
  def hist(transform, dimensions, nbins):```
``````

**Comment by franknoe** [comment] 2015-09-28 02:17
Indeed there seems to be a problem with the bhmm dependency in the 
git-based install. @marscher, can you handle this?

Am 28/09/15 um 02:47 schrieb Eugen Hruska:

> Not sure what this was, but I installed bhmm separately, reinstalled 
> everything and it works.
> It just gives an warning:
> 
> |/home/eh22/modules/PyEMMA/pyemma/coordinates/util/stat.py:31: 
> DeprecationWarning: Call to deprecated function hist. Called from 
> pyemma.coordinates.util.stat line 31. Please use 
> pyemma.coordinates.histogram() def hist(transform, dimensions, 
> nbins):``` |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/567#issuecomment-143607805.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-09-28 13:00
This is a known issue which should have been patched in a recent setuptools version. But from your output I guess that setuptools upgraded itself during the setup process. Can you confirm this? Do you experience the same thing, if you manually upgrade setuptools prior the installation of pyemma? I've tested it locally in a clean environment and it seems to work with setuptool-18.3.2.

This issue is being caused by a bug in Cython, which does not handle the extension class of setuptools (but only the distutils version).

We can require a more recent version (>=18) in our setup to avoid this.

**Comment by euhruska** [comment] 2015-09-28 13:40
Can't find a command to figure which setuptool I'm using now.
What about the warning: `Call to deprecated function hist. Called from pyemma.coordinates.util.stat line 31. Please use pyemma.coordinates.histogram()
  def hist(transform, dimensions, nbins):` ?

**Comment by marscher** [comment] 2015-09-28 13:57
the setuptools version can be obtained by

```
python -c "import setuptools; print setuptools.__version__"
```

The deprecation warning is being triggered on import no matter if you use this function or not. This is a bug fixed by #563. You can safely ignore it.

**Comment by franknoe** [comment] 2015-09-28 13:59
I'll put this in a new issue.

Am 28/09/15 um 15:40 schrieb Eugen Hruska:

> |Call to deprecated function hist. Called from 
> pyemma.coordinates.util.stat line 31. Please use 
> pyemma.coordinates.histogram()
> def hist(transform, dimensions, nbins):| ?

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by euhruska** [comment] 2015-09-28 14:36
I have now setuptools 11.3.1

**Comment by franknoe** [comment] 2015-09-28 14:38
18 and 11. Wow, are they releasing a new version every month?
Can we track back since which setuptool version this bug was fixed?

Am 28/09/15 um 15:00 schrieb Martin K. Scherer:

> This is a known issue which should have been patched in a recent 
> setuptools version. But from your output I guess that setuptools 
> upgraded itself during the setup process. Can you confirm this? Do you 
> experience the same thing, if you manually upgrade setuptools prior 
> the installation of pyemma? I've tested it locally in a clean 
> environment and it seems to work with setuptool-18.3.2.
> 
> This issue is being caused by a bug in Cython, which does not handle 
> the extension class of setuptools (but only the distutils version).
> 
> We can require a more recent version (>=18) in our setup to avoid this.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/567#issuecomment-143737414.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-09-28 14:41
Am 28.09.2015 um 16:38 schrieb Frank Noe:

> 18 and 11. Wow, are they releasing a new version every month?
> Can we track back since which setuptool version this bug was fixed?
> They follow the same release/versioning policy like us: 
> API/Functionality breakage -> new major version.

According to their changelog, they have changed the Cython handling in 
version 18.

**Comment by franknoe** [comment] 2015-09-28 14:46
OK, then I guess we have to require that...

Am 28/09/15 um 16:41 schrieb Martin K. Scherer:

> Am 28.09.2015 um 16:38 schrieb Frank Noe:
> 
> > 18 and 11. Wow, are they releasing a new version every month?
> > Can we track back since which setuptool version this bug was fixed?
> > They follow the same release/versioning policy like us:
> > API/Functionality breakage -> new major version.
> 
> According to their changelog, they have changed the Cython handling in
> version 18.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/567#issuecomment-143762963.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment] 2015-10-09 20:11
@marscher is this resolved?

**Closed as completed** 2015-10-13 15:22 UTC
