### ISSUE TITLE
Help wanted: tutorials of TRAM analyzing biased (e.g. umbrella sampling or metadynamics) simulations with PyEMMA?

### ISSUE THREAD

**Issue by yongwangCPH** [markovmodel/PyEMMA#1014] opened 2016-12-23 22:59 UTC
I'd like to do MSM analysis on biased simulations (using umbrella sampling or metadynamics), but didn't find any tutorials for it. Could you show me where I could find one or provide me one (like dialanine or a bit more complex biological system)? Thanks a lot! And merry christmas in advance!

**Comment by franknoe** [comment] 2017-01-02 15:24
Happy new year! I suggest @cwehmeyer to help with this.

**Comment by fabian-paul** [comment] 2017-01-02 18:08
Hi @franknoe, a while ago we discussed whether we could provide the US-data from the Trypsin-Benzamidine system as a tutorial. The advantage is that the data is very low-dimensional (only the US-order parameter and one TICA dimension). The disadvantage is, that it's pure US-data without physical kinetics. And it's not so interesting if one doesn't have the full trajectories (e. g. to look at them in VMD and study the binding pathway). What do you think?

**Comment by franknoe** [comment] 2017-01-02 18:14
Yeah, if we reduce the data to two dimensions, it's similar to a alanine dipeptide example. Don't we have a tutorial for that? Perhaps not US?

**Comment by yongwangCPH** [comment] 2017-01-09 10:05
Happy new years. Thanks for your reply. Just let me know when the tutorial is ready.

**Comment by liyigerry** [comment] 2017-08-08 02:46
Is the tutorial ready for metadynamics with pyemma 2.4?
I find the pyemma.thermo.estimate_umbrella_sampling. Is it can be used for metadynamics which is the special case of US?

**Comment by liyigerry** [comment] 2017-08-08 02:48
@cwehmeyer

**Comment by fabian-paul** [comment] 2017-08-11 17:50
You can try to use the `tram()` function directly, if you know how to compute the bias.
Like this:
https://gist.github.com/fabian-paul/b14793bea0bf0014c1c1a2e48e24e61f
No guarantees for correctness, yet. Example may still contain bugs. But this might get you started.

**Comment by liyigerry** [comment] 2017-08-12 03:13
@fabian-paul Thanks. I will try it and report in case of errors.

**Comment by liyigerry** [comment] 2017-08-15 08:25
@fabian-paul 

I have run the metadyanmics by PLUMED with CV1/2, adding the bias at each simulation time.

Firstly, I have clusterd the trajectory based on CV1 and CV2, gettiing the Markov state, dtrajs.

For my understanding, I have clustered the bias sequences with the same cluster number of dtrajs, getting the therm state, ttrajs.

When I run tram, I got the error
```
/pyemma/thermo/estimators/TRAM_estimator.pyc in _estimate(self, X)
    256         for t, d, b, in zip(ttrajs, dtrajs_full, btrajs):
    257             assert t.shape[0] == d.shape[0] == b.shape[0]
--> 258             assert b.shape[1] == self.nthermo
    259 
    260         # cast types and change axis order if needed

AssertionError: 
```

**Comment by fabian-paul** [comment] 2017-08-28 10:00
Hi  liyigerry,

Sorry for the late reply. Can you please send a full example with full information about the input parameters that you give to Pyemma? The problem is not clear form the error message, that you send.

What do you mean with "bias sequence"? There are two related but different sequences that are related to bias:

* the index i(t) of the thermodynamic state (ensemble) in which a given MD frame x(t) was generated.
  These indices form a time series that has to be given to the TRAM method in the `ttrajs` argument.

  In the case of metadynamics this should correspond to the number is deposited Gaussians at time t.
 
* the bias energies of the MD frame x(t) evaluated in all ensembles b^k(x(t)) for k in 0...(K-1). These should be given to TRAM as the `btrajs` argument. In the case of metadynamics the bias energy of ensemble k is defined as the sum of the first k Gaussians (summed in the same order as they were deposited in the simulation). The table of bias energies `b` has the shape (T, N) where N is the maximum number of deposited Gaussians (in the end of the simulation) and T is the number frames (possibly after applying a stride). The element b[t,k] of that table is computed by  b[t, k] = \sum_0^k g(x(t), m_i, sigma_i) where g is the Gauss function as defined in PLUMED and m_i and sigma_i are the parameters of the i'th Gaussian. b[t, 0]=0 for all t.

Note that almost all method parameters in Pyemma that are related to time series assume that you supply a list of time series (since the default assumption is Pyemma is that you have run multiple independent simulations). If you only ran one metadynamics simulations, you still have to wrap the arguments that you give to Pyemma in lists.
ttrajs=[time_series_of_index_of_the_thermodynamic_state_for_my_single_metadynamics_simulation]
btrajs=[table_of_bias_energies_for_my_single_metadynamics_simulation]

Best
Fabian

**Comment by liyigerry** [comment] 2017-08-29 06:42
@fabian-paul Thanks for your detailed reply.

I can not understand what you mean about ttrajs and dtrajs generated from metadynamics without examples. 
Can I using clustering method to get ttrajs and dtrajs?
And how to achieve the bias for tram?

I upload my data at [meta_pyemma_example](https://github.com/liyigerry/meta_pyemma_example) and ipython notebook [gist](https://gist.github.com/liyigerry/3b6b80a671003d268dd9f5cbbf23587b).

Can you bring a plumed-files-related example or work on my data?

I select two distance between the center of mass of atom groups as collective variables (CVs), and then run using well-temper method with Gromacs, seeing plumed.dat.

After simulation, I got these following files:
1. CVS, which contain CVs as time evolution.
2. HILLS_CVS, which contain the bias added during the simulation
3. fes.dat, which generated by run plumed driver method.

Waiting for your help. Thanks.

Li Yi

**Comment by marscher** [comment] 2018-01-16 13:18
closing staled discussion

**Closed as completed by marscher** 2018-01-16 13:18 UTC
Labels: thermo
