### ISSUE TITLE
xtc opening error that occurs *sometimes*

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#306] opened 2015-05-13 13:38 UTC
This might be hard to reproduce. We have run into the following issue:
- use mdtraj to create an xtc file, e.g. by reading another file and writing a subset of frames to an xtc output
- use emma in order to load/source that file. The error below is thrown.
- It looks like this must be done more or less subsequently in the same notebook.

I am not actually sure if this is sufficient to reproduce the error, please try. My guess is that maybe mdtraj doesn't close the file while writing to an xtc (perhaps you have to do it explicitly?), and then the file is somehow locked and cannot be opened. I would still thing that read access should be possible though.

The xtc file itself is OK. Reading it later (e.g. in a different or restarted notebook) works fine.

``` python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-97-f308f630d44f> in <module>()
      1 import pyemma.coordinates
----> 2 coords_every50 = pyemma.coordinates.load(xtc_list,top = 'DESRES-Trajectory/firstframe.pdb',stride = 50)

/Users/cecilia/anaconda/lib/python2.7/site-packages/pyEMMA-1.2-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/api.pyc in load(trajfiles, features, top, stride)
    150         isinstance(trajfiles, (list, tuple))
    151             and (any(isinstance(item, basestring) for item in trajfiles) or len(trajfiles) is 0)):
--> 152         reader = _create_file_reader(trajfiles, top, features)
    153         trajs = reader.get_output(stride=stride)
    154         if len(trajs) == 1:

/Users/cecilia/anaconda/lib/python2.7/site-packages/pyEMMA-1.2-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/data/util/reader_utils.pyc in create_file_reader(input_files, topology, featurizer)
     62                                          "featurizer or a topology file.")
     63 
---> 64                     reader = _FeatureReader(input_list, featurizer=featurizer, topologyfile=topology)
     65                 else:
     66                     if suffix in ['.npy', '.npz']:

/Users/cecilia/anaconda/lib/python2.7/site-packages/pyEMMA-1.2-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/data/feature_reader.pyc in __init__(self, trajectories, topologyfile, chunksize, featurizer)
     80         self._Y = None
     81 
---> 82         self.__set_dimensions_and_lenghts()
     83         self._parametrized = True
     84 

/Users/cecilia/anaconda/lib/python2.7/site-packages/pyEMMA-1.2-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/data/feature_reader.pyc in __set_dimensions_and_lenghts(self)
     95         # basic statistics
     96         for traj in self.trajfiles:
---> 97             sum_frames = sum(t.n_frames for t in self._create_iter(traj))
     98             self._lengths.append(sum_frames)
     99 

/Users/cecilia/anaconda/lib/python2.7/site-packages/pyEMMA-1.2-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/data/feature_reader.pyc in <genexpr>((t,))
     95         # basic statistics
     96         for traj in self.trajfiles:
---> 97             sum_frames = sum(t.n_frames for t in self._create_iter(traj))
     98             self._lengths.append(sum_frames)
     99 

/Users/cecilia/anaconda/lib/python2.7/site-packages/pyEMMA-1.2-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/util/patches.pyc in iterload(filename, chunk, **kwargs)
    130                         raise StopIteration()
    131                 while True:
--> 132                     xyz, time, step, box = f.read(chunk*stride, stride=stride, atom_indices=atom_indices)
    133                     if len(xyz) == 0:
    134                         raise StopIteration()

xtc.pyx in xtc.XTCTrajectoryFile.read (mdtraj/formats/xtc/xtc.c:3970)()

xtc.pyx in xtc.XTCTrajectoryFile._read (mdtraj/formats/xtc/xtc.c:5988)()

RuntimeError: XTC read error: Compressed 3d coordinate
```

**Comment by marscher** [comment] 2015-05-13 13:43
your intuition might be correct, that this is caused by not closing the
files. In dev_release_1.2.1 files are being closed correctly.

It depends on how you've written the file. If it has not been closed, it
also might no be flushed yet (all changes are written back to disk).

If you use Python's concept of ContextManagers:

with XTCTrajectoryFile("myfile.xtc", mode='w') as fh:
    fh.write(traj)

then it gets closed after the with block automatically.

**Comment by marscher** [comment] 2015-05-13 13:51
If the trajectory is broken due to not closed file handle during writing, the error would be reproducible. So we can exclude that.

**Comment by franknoe** [comment] 2015-05-13 13:51
Am 13/05/15 um 15:43 schrieb Martin K. Scherer:

> your intuition might be correct, that this is caused by not closing the
> files. In dev_release_1.2.1 files are being closed correctly.
> Note that we have created the file with mdtraj, not with EMMA, so it 
> might be not an EMMA issue.

Here is the mdtraj code used for writing:

```
import mdtraj

topfile = 'DESRES-Trajectory/firstframe.pdb'
outfile1 = 'all_fip35every50_1.xtc'
outtraj1 = mdtraj.open(outfile1, mode='w')
outfile2 = 'all_fip35every50_2.xtc'
outtraj2 = mdtraj.open(outfile2, mode='w')

reftraj = mdtraj.load('native.pdb')

stride = 50

for x in [1]:
     for y in range(0,50):
         infile = 
'DESRES-Trajectory/ww_'+str(x)+'-protein-0'+str(y).zfill(2)+'.dcd'
         print 'reading :',infile
         intraj = mdtraj.load(infile, stride=stride, top=topfile)
         intraj.superpose(reftraj, frame=0)
         outtraj1.write(intraj.xyz)

for x in [2]:
     for y in range(0,50):
         infile = 
'DESRES-Trajectory/ww_'+str(x)+'-protein-0'+str(y).zfill(2)+'.dcd'
         print 'reading :',infile
         intraj = mdtraj.load(infile, stride=stride, top=topfile)
         intraj.superpose(reftraj, frame=0)
         outtraj2.write(intraj.xyz)
```

I've been looking for a close() function, but have not found any.

> It depends on how you've written the file. If it has not been closed, it
> also might no be flushed yet (all changes are written back to disk).
> That makes sense. Do you think that is an issue in the code above?
> 
> If you use Python's concept of ContextManagers:
> 
> with XTCTrajectoryFile("myfile.xtc", mode='w') as fh:
> fh.write(traj)
> Hm, I don't know that concept. What is different from the code above, 
> and what causes the file to be closed in this code?
> 
> then it gets closed after the with block automatically.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/306#issuecomment-101667747.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-05-13 13:52
outtraj1.close()

should do the job.

**Comment by franknoe** [comment] 2015-05-13 13:57
Ha. The close() function is actually not documented in mdtraj, but seems to exist. We should post an issue about this.

In any case that did not fix the problem. The same error occurs. Weird.

**Comment by franknoe** [comment] 2015-05-13 13:59
Can you try to reproduce the error by using one of our trajectories (e.g. the BPTI data), writing in a way similar to the above, and then trying to load/source it?
My connection is really weak here, so I cannot upload a trajectory at the moment.

**Comment by marscher** [comment] 2015-05-13 13:59
The deal with ContextManager is that the resource created within the with statement gets cleanup as soon as the with block is finished. So if a class implements the context manager protocol with **enter**() and **exit** methods, it is able to eg. close its file handles.

**Comment by marscher** [comment] 2015-05-13 14:00
```
 outtraj1.write(intraj.xyz)
```

that might be the error. You should not pass the coordinates but the complete objects.

**Comment by marscher** [comment] 2015-05-13 14:01
mhm, no its coordinates - sorry.

**Comment by marscher** [comment] 2015-05-13 14:02
Close function is documented:

http://mdtraj.org/latest/api/generated/mdtraj.formats.XTCTrajectoryFile.html?highlight=xtctrajectoryfile#mdtraj.formats.XTCTrajectoryFile.close

**Comment by franknoe** [comment] 2015-05-13 14:02
No, that creates an error. It wants the numpy array.

Am 13/05/15 um 16:00 schrieb Martin K. Scherer:

> |  outtraj1.write(intraj.xyz)
> |
> 
> that might be the error. You should not pass the coordinates but the 
> complete objects.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/306#issuecomment-101672589.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment] 2015-05-13 14:04
Ah, I was looking for it in the Trajectory object.

Am 13/05/15 um 16:02 schrieb Martin K. Scherer:

> Close function is documented:
> 
> http://mdtraj.org/latest/api/generated/mdtraj.formats.XTCTrajectoryFile.html?highlight=xtctrajectoryfile#mdtraj.formats.XTCTrajectoryFile.close
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/306#issuecomment-101673251.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-05-13 14:08
Are your written files readable with VMD?

**Comment by franknoe** [comment] 2015-05-13 14:11
Yes, VMD can read it! And a subsequent attempt to source/load again failed with the same error.

**Comment by marscher** [comment] 2015-05-13 14:13
What makes me curious: your outfile has .dcd extension, but your error originates from XTCFileTrajectory.

**Comment by marscher** [comment] 2015-05-13 14:14
but we're using the same extension->reader binding as mdtraj (we're importing their format registry)...

**Comment by franknoe** [comment] 2015-05-13 14:19
I am sorry for the confusion - there was a code change just before sending the email. With dcd it works, with xtc the problem exists. I changed the code above to xtc.

**Comment by marscher** [comment] 2015-05-13 14:25
I assume there are not topology changes in the input files, since I'm not sure if mdtraj checks for that. Maybe store the shapes of xyz in a set and see if there is only element. Sorry I'm only able to guess right now and happy birthday by the way!!

**Comment by franknoe** [comment] 2015-05-13 14:27
Am 13/05/15 um 16:25 schrieb Martin K. Scherer:

> I assume there are not topology changes in the input files, since I'm 
> not sure if mdtraj checks for that. Maybe store the shapes of xyz in a 
> set and see if there is only element.
> 
> I don't think that's the issue. We can read the correct structures into 
> VMD. We have not made any topology changes either.
> 
> Sorry I'm only able to guess right now
> 
> Yes, I guess you have to try to reproduce the error on your machine in 
> order to track it down.
> 
> and happy birthday by the way!!
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/306#issuecomment-101684959.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-05-13 15:04
mdtraj and VMD are using the same C library to perform reading - very
confusing that VMD was able tor read those files then, while mdtraj failed.

**Comment by marscher** [comment] 2015-06-15 10:48
I consider this a not easy to reproduce bug in mdtraj and will close it now.

**Closed as completed by marscher** 2015-06-15 10:48 UTC
