### ISSUE TITLE
[devel] fatal error: theobald_rmsd.h: No such file or directory

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#763] opened 2016-04-06 14:09 UTC
I am lazily copy-pasting the error, I'm guessing it's something very obvious that I've overlooked:

```
gph82@southsea:  ~/programs/PyEmma$ git pull
Already up-to-date.
gph82@southsea:  ~/programs/PyEmma$ python setup.py develop
setup.py:255: UserWarning: using git, require cython
  warnings.warn('using git, require cython')
running develop
creating /tmp/hasfunction-77qaz5mq/tmp
creating /tmp/hasfunction-77qaz5mq/tmp/hasfunction-77qaz5mq
cc -c /tmp/hasfunction-77qaz5mq/funcname.c -o /tmp/hasfunction-77qaz5mq/tmp/hasfunction-77qaz5mq/funcname.o
cc /tmp/hasfunction-77qaz5mq/tmp/hasfunction-77qaz5mq/funcname.o -o /tmp/hasfunction-77qaz5mq/a.out
creating /tmp/hasfunction-_fayoipg/tmp
creating /tmp/hasfunction-_fayoipg/tmp/hasfunction-_fayoipg
cc -c /tmp/hasfunction-_fayoipg/funcname.c -o /tmp/hasfunction-_fayoipg/tmp/hasfunction-_fayoipg/funcname.o
cc /tmp/hasfunction-_fayoipg/tmp/hasfunction-_fayoipg/funcname.o -lgomp -o /tmp/hasfunction-_fayoipg/a.out
setup.py:153: UserWarning: enabled openmp
  warnings.warn('enabled openmp')
running egg_info
writing requirements to pyEMMA.egg-info/requires.txt
writing pyEMMA.egg-info/PKG-INFO
writing dependency_links to pyEMMA.egg-info/dependency_links.txt
writing top-level names to pyEMMA.egg-info/top_level.txt
writing pbr to pyEMMA.egg-info/pbr.json
reading manifest file 'pyEMMA.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'testfiles/*' under directory 'pyemma'
warning: no previously-included files matching 'git' found under directory '*'
no previously-included directories found matching '.eggs'
writing manifest file 'pyEMMA.egg-info/SOURCES.txt'
running build_ext
building 'pyemma.coordinates.clustering.kmeans_clustering' extension
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_OPENMP -I/home/mi/gph82/programs/mdtraj/mdtraj/core/lib -I/home/mi/gph82/miniconda3/lib/python3.4/site-packages/numpy/core/include -Ipyemma/coordinates/clustering/include -I/home/mi/gph82/miniconda3/include/python3.4m -c pyemma/coordinates/clustering/src/kmeans.c -o build/temp.linux-x86_64-3.4/pyemma/coordinates/clustering/src/kmeans.o -std=c99 -fopenmp
In file included from /home/mi/gph82/miniconda3/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                 from /home/mi/gph82/miniconda3/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/mi/gph82/miniconda3/lib/python3.4/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pyemma/coordinates/clustering/include/clustering.h:27,
                 from pyemma/coordinates/clustering/src/kmeans.c:20:
/home/mi/gph82/miniconda3/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from pyemma/coordinates/clustering/src/kmeans.c:20:0:
pyemma/coordinates/clustering/include/clustering.h:36:27: fatal error: theobald_rmsd.h: No such file or directory
 #include <theobald_rmsd.h>
                           ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```

**Comment by marscher** [comment] 2016-04-07 12:29
Do you have mdtraj installed? The missing header is coming from the installed package.

**Comment by gph82** [comment] 2016-04-07 13:48
Hello @marscher , @fabian-paul helped me out a bit yesterday. I think it had to to with the development version of mdtraj, which does not have theobald_rmsd.h in -I/home/mi/gph82/programs/mdtraj/mdtraj/core/lib but elsewhere

**Comment by marscher** [comment] 2016-04-07 13:54
So they moved the header somewhere else? I think mdtraj provided an api function to get the include directory.

**Comment by marscher** [comment] 2016-04-07 13:55
mdtraj.capi()['include_dir'] used to be the proper location. So can you confirm that this has been changed on latest master of mdtraj?

**Comment by gph82** [comment] 2016-04-07 13:59
I'm not sure this is the answer you're looking for but in the devel version :
- there's no more lib directory in mdtraj/core anymore (https://github.com/mdtraj/mdtraj/tree/master/mdtraj/core)
- there's an rmsd directory in mdtraj

**Comment by gph82** [comment] 2016-04-07 14:00
In 1.6, mdtraj.capi()["include_dir"]
returns the address of the version installed with pyemma:
/home/mi/gph82/programs/PyEmma/.eggs/mdtraj-1.6.1-py3.4-linux-x86_64.egg/mdtraj/core/lib

I guess I was trying to use the devel version with pyemma too soon ?

**Comment by marscher** [comment] 2016-04-07 14:07
Am 07.04.2016 um 16:00 schrieb Guillermo Pérez-Hernández:

**Comment by gph82** [comment] 2016-04-07 14:13
the location /home/mi/gph82/programs/PyEmma/.eggs/mdtraj-1.6.1-py3.4-linux-x86_64.egg is a proper build of mdtraj with all subdirs etc.

I guess the hardest test would be to install the devel version of mdtraj, then try to install pyemma?

**Comment by marscher** [comment] 2016-04-07 14:23
yes

**Comment by fabian-paul** [comment] 2016-04-11 13:35
If i understand correctly, the core/lib directory is created only when mdtraj is installed.
When requesting mdtraj.capi()["include_dir"], are we in fact making sure that mdtraj is the freshly installed version (which might have been installed during the same setup.py develop call?)

**Comment by marscher** [comment] 2016-04-12 12:46
It should be the latest version (at least with respect to the version constraints we've set in setup.py). I am also using a development version of mdtraj and can not reproduce this.

From with the mdtraj dev directory ipython shell:

```
In [1]: import mdtraj, os
In [3]: mdtraj.capi()
Out[3]: {'include_dir': 'mdtraj/core/lib', 'lib_dir': 'mdtraj/core/lib'}
In [5]: os.path.exists(mdtraj.capi()['include_dir'])
Out[5]: True
```

This also works from different locations to start ipython from. It should not matter if mdtraj is loosely installed in the local .eggs directory, since it should be a properly installed version and therefore have the core/lib directory.

**Comment by gph82** [comment] 2016-04-18 09:14
this went away with current devel version of both pyemma and mdtraj, cannot reproduce anymore. I'm closing

**Comment by gph82** [comment] 2016-04-19 07:35
here we go again....

**Comment by gph82** [comment] 2016-04-19 07:38
For some reason, the mdtraj devel version is giving problems here..., had to "hide" my devel version (mv mdtraj mdtraj_bak) and run python setup.py develop (of pyemma) s.t. pyemma would get an older mdtraj version

**Comment by marscher** [comment] 2016-05-09 10:26
I blame mdtraj for this, since these headers are public API of mdtraj. You should report upstream. The error seems to be that the headers are not exported during setup.py develop (which itself invokes build_ext)

Pinging @mpharrigan

**Comment by franknoe** [comment] 2016-05-09 10:30
So it works with `setup.py install` but not with `setup.py develop`? 
That's strange, because I've never run into this error, although I 
always install things from the source with `develop` option. I agree 
we should discuss this issue with the mdtraj folks, probably it's a very 
minor fix for them if the header isn't exported in some specific scenario.

Am 09/05/16 um 12:26 schrieb Martin K. Scherer:

> I blame mdtraj for this, since these headers are public API of mdtraj. 
> You should report upstream. The error seems to be that the headers are 
> not exported during setup.py develop (which itself invokes build_ext)
> 
> Pinging @mpharrigan https://github.com/mpharrigan
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/763#issuecomment-217829369

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment] 2016-05-09 11:29
problem was with the mdtraj dev version, which I had at the moment. I have not tried yet with the new conda release. I'll report back soon.

**Comment by marscher** [comment] 2016-05-14 14:48
Should be fixed upon merge of https://github.com/mdtraj/mdtraj/pull/1118

**Comment by marscher** [comment] 2016-05-14 18:53
fixed.

**Closed as completed by marscher** 2016-05-14 18:53 UTC
Labels: upstream
