### ISSUE TITLE
RuntimeError: call _progress_register(amount_of_work, stage=1) on this instance first!

### ISSUE THREAD

**Issue by danielSoler93** [markovmodel/PyEMMA#1213] opened 2018-01-05 08:40 UTC
Thanks for submitting an issue!

ERROR:
--------------

When clustering via kmeans an unexpeted error attached at the end of the e-mail shows up. It looks something related with the progress bar that is built in paralel using OMP_THREADS=3. (Look the file attached for more information).

PyeMMA & OS:
----------------------

PyEMMA version: 2.4

OS: 
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

Script and error attached as script.ppy.tar.gz & error.txt
---------------------------------------------------------------------------

[error.txt](https://github.com/markovmodel/PyEMMA/files/1605934/error.txt)

[script.py.tar.gz](https://github.com/markovmodel/PyEMMA/files/1605939/script.py.tar.gz)

My pip list:
----------------

[environment.txt](https://github.com/markovmodel/PyEMMA/files/1605921/environment.txt)

**Comment by marscher** [comment] 2018-01-06 15:29
thanks, we have solved this problem already for the conda-version. But it would have required a new release for pip. Please downgrade progress_reporter to 1.3.1

Duplicate of #1201

**Closed as completed by marscher** 2018-01-06 15:29 UTC
Labels: duplicate
