### ISSUE TITLE
reading in of .xyz trajectory fails

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#621] opened 2015-11-09 16:18 UTC
I have a problem with reading in .xyz trajectory files. 
The example I am trying to run looks like:

```
import pyemma
import pyemma.coordinates as coor
import pyemma.msm as msm
import pyemma.plots as mplt
import numpy as np

print pyemma.__version__

topfile = 'adp.pdb'
traj_list = ['chain.xyz']
feat = coor.featurizer(topfile)
feat.add_dihedrals([[14,16,0,2],[12,14,16,0]],deg=True,cossin=False)
inp = coor.source(traj_list, feat)
print 'number of trajectories = ',inp.number_of_trajectories()
print 'trajectory length = ',inp.trajectory_length(0)
print 'trajectory time step = ',500.0 / (inp.trajectory_length(0)-1),'ns'
print 'number of dimension = ',inp.dimension()
```

The output I get is:

```
/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/util/stat.py:31: DeprecationWarning: Call to deprecated function hist. Called from pyemma.coordinates.util.stat line 31. Please use pyemma.coordinates.histogram()
  def hist(transform, dimensions, nbins):
2.0.1-18-gf8aa02c
Traceback (most recent call last):
  File "minimal_example.py", line 15, in <module>
    inp = coor.source(traj_list, feat)
  File "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/api.py", line 347, in source
    reader = _create_file_reader(inp, top, features, chunk_size=chunk_size if chunk_size else 100)
  File "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/util/reader_utils.py", line 92, in create_file_reader
    chunksize=chunk_size)
  File "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/feature_reader.py", line 107, in __init__
    self.__set_dimensions_and_lengths()
  File "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/feature_reader.py", line 116, in __set_dimensions_and_lengths
    self._lengths.append(TrajectoryInfoCache[traj])
  File "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/traj_info_cache.py", line 70, in __getitem__
    result = self.__determine_len(filename)
  File "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/traj_info_cache.py", line 76, in __determine_len
    return len(fh)
  File "/Users/toni_brain/miniconda/lib/python2.7/site-packages/mdtraj/formats/xyzfile.py", line 386, in __len__
    raise NotImplementedError()
NotImplementedError
```

A workaround that works is, to load the .xyz file into mdtraj and then convert it to .xtc, save that file and read this into pyemma instead:

```
#Now instead we could load this into mdtraj and then convert to xtc.
#If this xtc is then read into pyemma everything works fine.
import mdtraj as md
traj = md.load('chain.xyz', top='adp.pdb')
traj.save_xtc('chain_mod.xtc')
```

I have attached the .pdb and .xyz files. (renamed with extension .txt for both cases)
[adp.txt](https://github.com/markovmodel/PyEMMA/files/30111/adp.txt)
[chain.txt](https://github.com/markovmodel/PyEMMA/files/30110/chain.txt)

**Comment by marscher** [comment] 2015-11-09 16:23
This is caused by an unsupported call to len(traj) in xyz format, which is related to mdtraj. Obviously we've not tested xyz format (ascii based, right?).

As a workaround you can also turn of the trajectory length cache in your config file and see if it fixes the problem. The file is located in ~/.pyemma/pyemma.cfg and is pretty much self explanatory.

Thanks for reporting this, but actually you and we would be better of, if you report it upstream in mdtraj.

**Comment by franknoe** [comment] 2015-11-09 16:25
Thanks for reporting! I think we had discussed to make loading tests for 
various formats - do we have that?

If xyz cannot be supported for some reason (e.g. because the length 
needs to be accessible), we should tell the user.

Am 09/11/15 um 17:18 schrieb ppxasjsm:

> I have a problem with reading in .xyz trajectory files.
> The example I am trying to run looks like:
> 
> |import pyemma import pyemma.coordinates as coor import pyemma.msm as 
> msm import pyemma.plots as mplt import numpy as np print 
> pyemma.**version** topfile = 'adp.pdb' traj_list = ['chain.xyz'] feat 
> = coor.featurizer(topfile) 
> feat.add_dihedrals([[14,16,0,2],[12,14,16,0]],deg=True,cossin=False) 
> inp = coor.source(traj_list, feat) print 'number of trajectories = 
> ',inp.number_of_trajectories() print 'trajectory length = 
> ',inp.trajectory_length(0) print 'trajectory time step = ',500.0 / 
> (inp.trajectory_length(0)-1),'ns' print 'number of dimension = 
> ',inp.dimension() |
> 
> The output I get is:
> 
> |/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/util/stat.py:31: 
> DeprecationWarning: Call to deprecated function hist. Called from 
> pyemma.coordinates.util.stat line 31. Please use 
> pyemma.coordinates.histogram() def hist(transform, dimensions, nbins): 
> 2.0.1-18-gf8aa02c Traceback (most recent call last): File 
> "minimal_example.py", line 15, in <module> inp = 
> coor.source(traj_list, feat) File 
> "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/api.py", 
> line 347, in source reader = _create_file_reader(inp, top, features, 
> chunk_size=chunk_size if chunk_size else 100) File 
> "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/util/reader_utils.py", 
> line 92, in create_file_reader chunksize=chunk_size) File 
> "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/feature_reader.py", 
> line 107, in __init__ self.**set_dimensions_and_lengths() File 
> "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/feature_reader.py", 
> line 116, in __set_dimensions_and_lengths 
> self._lengths.append(TrajectoryInfoCache[traj]) File 
> "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/traj_info_cache.py", 
> line 70, in __getitem** result = self.**determine_len(filename) File 
> "/Users/toni_brain/Projects/git/PyEMMA/pyemma/coordinates/data/traj_info_cache.py", 
> line 76, in __determine_len return len(fh) File 
> "/Users/toni_brain/miniconda/lib/python2.7/site-packages/mdtraj/formats/xyzfile.py", 
> line 386, in __len** raise NotImplementedError() NotImplementedError |
> 
> A workaround that works is, to load the .xyz file into mdtraj and then 
> convert it to .xtc, save that file and read this into pyemma instead:
> 
> |#Now instead we could load this into mdtraj and then convert to xtc. 
> #If this xtc is then read into pyemma everything works fine. import 
> mdtraj as md traj = md.load('chain.xyz', top='adp.pdb') 
> traj.save_xtc('chain_mod.xtc') |
> 
> I have attached the .pdb and .xyz files. (renamed with extension .txt 
> for both cases)
> adp.txt https://github.com/markovmodel/PyEMMA/files/30111/adp.txt
> chain.txt https://github.com/markovmodel/PyEMMA/files/30110/chain.txt
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/621.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-11-09 16:27
Yes we have, and we have implemented this for all formats which mdtraj is able to write (convert one dataset in various formats, test it).

**Comment by franknoe** [comment] 2015-11-09 16:28
Ah, so mdtraj can read but not write xyz?

Am 09/11/15 um 17:27 schrieb Martin K. Scherer:

> Yes we have, and we have implemented this for all formats which mdtraj 
> is able to write (convert one dataset in various formats, test it).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/621#issuecomment-155114241.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ppxasjsm** [comment] 2015-11-09 16:29
@marscher I can also report in mdtraj, however internally there is no problem loading the .xyz files with mdtraj it only is problematic with the pyemma dependency.

**Comment by marscher** [comment] 2015-11-09 16:30
IMHO it is a flaw in mdtraj, because the len operation is a mission crucial thing

**Comment by marscher** [comment] 2015-11-09 16:31
@franknoe At the time we wrote the test, this used to be the case.

**Comment by marscher** [comment] 2015-11-09 16:35
@ppxasjsm my mdtraj version supports len operation. So you're probably using something out dated. Try upgrading first.

**Comment by franknoe** [comment] 2015-11-09 16:39
OK. If we need the length operation, we should exclude xyz input and 
raise an informative exception. I agree that if xyz should be supported, 
the calculation of the length should be done in mdtraj. PyEMMA is not 
the place to do that.

I'm not sure if they want to add length support for xyz. I guess the xyz 
file format doesn't have such metainformation and one would need to read 
the entire file first to get it. Similar problem like making a catalogue 
of xtc files upon reading in order to have fast random access later. 
It's a matter of philosophy - instead of doing this you could also argue 
"why don't you use a decent file format instead of trying to emulate 
good behaviour with a crappy file format?".

I think I would support that viewpoint for xyz, and simply discourage to 
use it.

Am 09/11/15 um 17:31 schrieb Martin K. Scherer:

> @franknoe https://github.com/franknoe At the time we wrote the test, 
> this used to be the case.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/621#issuecomment-155115568.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment] 2015-11-09 16:39
ah, sorry that seems to go eliminate my last comment...

Am 09/11/15 um 17:35 schrieb Martin K. Scherer:

> @ppxasjsm https://github.com/ppxasjsm my mdtraj version supports len 
> operation. So you're probably using something out dated. Try upgrading 
> first.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/621#issuecomment-155116447.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-11-09 16:43
Na, I'm sorry, the way I've opened the file worked, but not the len operation on the plain file object (file abstraction layer of mdtraj).

**Comment by ppxasjsm** [comment] 2015-11-09 16:57
Interesting. I did a brand new miniconda download last week and installed pyemma. 
Looks like I just missed the mdtraj release. Now I did a
conda update pyemma

```
  File "test.py", line 1, in <module>
    import pyemma
  File "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/__init__.py", line 27, in <module>
    from . import coordinates
  File "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/__init__.py", line 107, in <module>
    from .api import *
  File "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/api.py", line 27, in <module>
    from pyemma.coordinates.pipelines import Discretizer as _Discretizer
  File "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/pipelines.py", line 22, in <module>
    from pyemma.coordinates.data.feature_reader import FeatureReader
  File "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/data/__init__.py", line 48, in <module>
    from .feature_reader import FeatureReader
  File "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/data/feature_reader.py", line 26, in <module>
    from pyemma.coordinates.data.featurizer import MDFeaturizer
  File "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/data/featurizer.py", line 21, in <module>
    from mdtraj.geometry.dihedral import _get_indices_phi, \
ImportError: cannot import name _get_indices_phi
```

**Comment by marscher** [comment] 2015-11-09 17:00
which build of pyemma is this? (eg. output of conda list| grep pyemma)

**Comment by ppxasjsm** [comment] 2015-11-09 17:00
@marscher: Exactly length is still not supported in mdtraj latest release, from the current master:

```
    def __len__(self):
        """Number of frames in the file. """
        raise NotImplementedError()
```

**Comment by gph82** [comment] 2015-11-09 17:01
This problem is fixed in devel, but not yet the conda release:
https://github.com/markovmodel/PyEMMA/pull/614

On 11/09/2015 05:57 PM, ppxasjsm wrote:

> Interesting. I did a brand new miniconda download last week and
> installed pyemma.
> Looks like I just missed the mdtraj release. Now I did a
> conda update pyemma
> 
> |File "test.py", line 1, in <module> import pyemma File
> "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/**init**.py",
> line 27, in <module> from . import coordinates File
> "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/**init**.py",
> line 107, in <module> from .api import \* File
> "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/api.py",
> line 27, in <module> from pyemma.coordinates.pipelines import
> Discretizer as _Discretizer File
> "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/pipelines.py",
> line 22, in <module> from pyemma.coordinates.data.feature_reader import
> FeatureReader File
> "/Users/toni_brain/miniconda/lib/python2.7/site-packages/pyemma/coordinates/data/__init__.py",
> line 48, in <module> from .feature_reader import FeatureReader File
> "/home/rbanisch/miniconda/lib/python2.7/site-packages/pyemma/coordinates/data/feature_reader.py",
> line 26, in <module> from pyemma.coordinates.data.featurizer import
> MDFeaturizer File
> "/home/rbanisch/miniconda/lib/python2.7/site-packages/pyemma/coordinates/data/featurizer.py",
> line 21, in <module> from mdtraj.geometry.dihedral import
> _get_indices_phi, \ ImportError: cannot import name _get_indices_phi |
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/621#issuecomment-155122392.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75775

## http://userpage.fu-berlin.de/gph82/

**Comment by ppxasjsm** [comment] 2015-11-09 17:04
So on OS X it is: 
pyemma                    2.0.2                    py27_0  

On Linux
pyemma                    2.0.1                    py27_1  

In both cases I used a conda update pyemma. In linux I get this rather unclear description:

```
Warning: 2 possible package resolutions (only showing differing packages):
    [u'mdtraj-1.5.1-np110py27_0.tar.bz2', u'pyemma-2.0.1-py27_1.tar.bz2'],
    [u'mdtraj-1.4.2-np110py27_1.tar.bz2', u'pyemma-2.0.1-py27_2.tar.bz2'],
```

**Comment by ppxasjsm** [comment] 2015-11-09 17:06
Same error now on both installation. If this is fixed in #614 that is fine. Though I somehow assume that the fix does not solve the original .xyz problem? Or does it?
I can use devel version instead.

**Comment by gph82** [comment] 2015-11-09 17:08
no, the original problem remains, sorry

**Comment by franknoe** [comment] 2015-11-09 17:14
If you have 2.0.2 then you should at the same time have mdtraj 1.5. Then 
this error
     cannot import name _get_indices_phi
should not occur anymore. Are you sure that this still happens for this 
version combo? Then something went wrong that we need to fix.

On you Linux install, probably the 2.0.2 build is not yet available and 
therefore it updated just the conda recipe for 2.0.1. Martin has done a 
quick fix trying to enforce mdtraj < 1.5 because 2.0.1 still uses mdtraj 
1.4 functionality. Apparently that has lead to the import confusion in 
your case. You could fix this by removing mdtraj 1.5, or you wait until 
2.0.2 is available on Linux, and then see above.

All of this has nothing to do with the xyz reading problem.

Am 09/11/15 um 18:04 schrieb ppxasjsm:

> So on OS X it is:
> pyemma 2.0.2 py27_0
> 
> On Linux
> pyemma 2.0.1 py27_1
> 
> In both cases I used a conda update pyemma. In linux I get this rather 
> unclear description:
> 
> |Warning: 2 possible package resolutions (only showing differing 
> packages): [u'mdtraj-1.5.1-np110py27_0.tar.bz2', 
> u'pyemma-2.0.1-py27_1.tar.bz2'], [u'mdtraj-1.4.2-np110py27_1.tar.bz2', 
> u'pyemma-2.0.1-py27_2.tar.bz2'], |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/621#issuecomment-155126207.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ppxasjsm** [comment] 2015-11-09 17:18
OsX version with 2.0.2 works fine. I was calling a 2.0.1 version. xyz error persists. 
Indeed the Linux build is still 2.0.1 with conda.

**Comment by franknoe** [comment] 2015-11-09 17:20
Alright. I think the easiest is to wait a little bit until the Linux 
build of 2.0.2 is available and then upgrade.

Am 09/11/15 um 18:18 schrieb ppxasjsm:

> OsX version with 2.0.2 works fine. I was calling a 2.0.1 version. xyz 
> error persists.
> Indeed the Linux build is still 2.0.1 with conda.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/621#issuecomment-155129973.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-11-09 17:27
The build infrastructure has been changed again (switched from Johns jenkins to docker container based travis builds, which now suffer from 40 min build time restriction...)

**Comment by franknoe** [comment] 2015-11-09 17:29
Wow, what is going on there ...

Am 09/11/15 um 18:27 schrieb Martin K. Scherer:

> The build infrastructure has been changed again (switched from John 
> jenkins to docker container based travis builds, which now suffer from 
> 40 min build time restriction...)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/621#issuecomment-155132424.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-11-20 01:03
https://github.com/mdtraj/mdtraj/issues/992 has been fixed upstream via reading the file once. So we can revert probably revert this (or continue to offer the workaround until the next mdtraj release).

**Comment by franknoe** [comment] 2015-11-20 08:03
I think we haven't released this feature yet. Thus, there is no harm in 
leaving it in our devel til the next mdtraj release if that happens 
before our 2.1 release.

To go one step furhter, we should fix #615 by either avoiding the use of 
protected attributes from mdtraj or asking them to make the needed 
attributes public (e.g. supported file types should be public in mdtraj)

Am 20/11/15 um 02:03 schrieb Martin K. Scherer:

> mdtraj/mdtraj#992 https://github.com/mdtraj/mdtraj/issues/992 has 
> been fixed upstream via reading the file once. So we can revert 
> probably revert this (or continue to offer the workaround until the 
> next mdtraj release).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/621#issuecomment-158247652.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment] 2015-11-20 13:07
This has nothing to do with calling private attributes (yes, **len** is a special attribute, but being called by a public interface: len). Of course there is no harm if this code stays on devel, but we have to keep it mind.

**Comment by franknoe** [comment] 2015-11-20 13:13
I know this is a different issue. The relation is in the note "until the 
mdtraj version changes".

Am 20/11/15 um 14:07 schrieb Martin K. Scherer:

> This has nothing to do with calling private attributes (yes, _len_ is 
> a special attribute, but being called by a public interface: len). Of 
> course there is no harm if this code stays on devel, but we have to 
> keep it mind.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/621#issuecomment-158396730.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Closed as completed** 2015-12-09 14:49 UTC
