### ISSUE TITLE
Error during clustering: TypeError: status_printer() takes from 1 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by eric-jm-lang** [markovmodel/PyEMMA#1303] opened 2018-05-21 14:46 UTC
Hello,

I am using PyEMMA installed via conda on a linux machine. I have attached a text file ([conda_list.txt](https://github.com/markovmodel/PyEMMA/files/2022936/conda_list.txt)) with the result of `conda list` command but here are the key points:

- Python version: 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) 
- numpy version: 1.12.1
- pyemma version: 2.5.2
- jupyter notebook version: 5.5.0

I am trying to run in a Jupyter Notebook the following command 
`clustering = pyemma.coordinates.cluster_kmeans(data=Y, k=n_clusters, stride=100)` do do a clustering (basically I am using the commands from the IO_features_02_pentapeptide_exercise.ipynb presented in February at the Berlin workshop, but for my own trajectories).

Running this command, I get the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-e47768c5d25d> in <module>()
----> 1 clustering = pyemma.coordinates.cluster_kmeans(data=Y, k=n_clusters, stride=100)

~/Software/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/api.py in cluster_kmeans(data, k, max_iter, tolerance, stride, metric, init_strategy, fixed_seed, n_jobs, chunksize, skip, keep_data, clustercenters, **kwargs)
   1813     cs = _check_old_chunksize_arg(chunksize, get_default_args(cluster_kmeans)['chunksize'], **kwargs)
   1814     if data is not None:
-> 1815         res.estimate(data, chunksize=cs)
   1816     else:
   1817         res.chunksize = cs

~/Software/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/transformer.py in estimate(self, X, **kwargs)
    210     """ Basis class for pipelined Transformers, which perform also estimation. """
    211     def estimate(self, X, **kwargs):
--> 212         super(StreamingEstimationTransformer, self).estimate(X, **kwargs)
    213         # we perform the mapping to memory exactly here, because a StreamingEstimator on its own
    214         # has not output to be mapped. Only the combination of Estimation/Transforming has this feature.

~/Software/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/streaming_estimator.py in estimate(self, X, chunksize, **kwargs)
     43         # run estimation
     44         try:
---> 45             super(StreamingEstimator, self).estimate(X, **kwargs)
     46         except NotConvergedWarning as ncw:
     47             self.logger.info(

~/Software/anaconda3/lib/python3.6/site-packages/pyemma/_base/estimator.py in estimate(self, X, **params)
    410         if params:
    411             self.set_params(**params)
--> 412         self._model = self._estimate(X)
    413         # ensure _estimate returned something
    414         assert self._model is not None

~/Software/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/clustering/kmeans.py in _estimate(self, iterable, **kw)
    203 
    204     def _estimate(self, iterable, **kw):
--> 205         self._init_estimate()
    206 
    207         # collect the data only if, we have not done this previously (eg. keep_data=True) or the centers are not initialized.

~/Software/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/clustering/kmeans.py in _init_estimate(self)
    282         if self.init_strategy == 'kmeans++':
    283             self._progress_register(self.n_clusters,
--> 284                                     description="initialize kmeans++ centers", stage=0)
    285         self._progress_register(self.max_iter, description="kmeans iterations", stage=1)
    286         self._init_in_memory_chunks(total_length)

~/Software/anaconda3/lib/python3.6/site-packages/pyemma/_base/progress/reporter/__init__.py in _progress_register(self, amount_of_work, description, stage, tqdm_args)
    143             if _attached_to_ipy_notebook_with_widgets():
    144                 from .notebook import my_tqdm_notebook
--> 145                 pg = my_tqdm_notebook(leave=False, **args)
    146             else:
    147                 import tqdm

~/Software/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm_notebook.py in __init__(self, *args, **kwargs)
    190         # Replace with IPython progress bar display (with correct total)
    191         self.sp = self.status_printer(
--> 192             self.fp, self.total, self.desc, self.ncols)
    193         self.desc = None  # trick to place description before the bar
    194 

TypeError: status_printer() takes from 1 to 3 positional arguments but 4 were given
```

So it looks like it is related to the progress bar which is not working.
Is there a way to fix this? Is it due to my installation/OS/version of a package, or is it a problem with PyEmma?
Alternatively, is there a way to disable the progress bar when using PyEmma? 

Many thanks in advance for your help!

**Comment by marscher** [comment] 2018-05-21 18:45
Thanks for your detailed report. This has already been fixed. Please run conda update pyemma

Duplicate of #1292

**Closed as completed by marscher** 2018-05-21 18:45 UTC
Labels: duplicate
